- name: Play Variables
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: Print Play Variables
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: Play Variables from Files
  hosts: localhost
  vars_files:
   - var.yml
  tasks:
   - name:  Print Variables from files
     ansible.builtin.debug:
       msg: "URL = variable from file {{ URL }}"
