- name: Play Variables
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: Print Play Variables
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: Play Variables from Files
  hosts: localhost
  vars_files:
   - var.yml
  tasks:
   - name:  Print Variables from files
     ansible.builtin.debug:
       msg: "URL = variable from file {{ URL }}"
- name: Tasks level variables
  hosts: localhost
  tasks:
    - name:  Print Variables of tasks
      vars:
         URL: task.example.com
      ansible.builtin.debug:
        msg: "URL = variable from task {{ URL }}, {{ansible_memfree_mb}}"
- name: Inventory level variables
  hosts: all
  tasks:
    - name:  Print Variables of Inventory
      ansible.builtin.debug:
        msg: "URL = variable from Inventory {{ URL }}, Hostname is {{ ansible_hostname }}"
- name: Runtime variable register
  hosts: localhost
  tasks:
    - name: Uptime output
      ansible.builtin.shell: uptime
      register: out

    - name: print stored variables
      ansible.builtin.debug:
        msg: "{{ out }}"
    - name: Declare a variable
      ansible.builtin.set_fact:
        status: "{{ out.rc }}"
